### ISSUE TITLE
Why migration not working after deploy?

### ISSUE THREAD

**Issue by zulhfreelancer** [mattbrictson/capistrano-mb#10]
After I deploy my app, I get this:

![0](https://cloud.githubusercontent.com/assets/3416976/16565091/9cb54ab0-423d-11e6-93ba-bede5a8eadb4.jpeg)

**Gemfile**

```
source 'https://rubygems.org'
ruby '2.3.1'

gem 'rails', '4.2.6'
gem 'sass-rails', '~> 4.0.3'
gem 'bootstrap-sass', '~> 3.2.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'devise'
gem 'acts_as_votable', '~> 0.10.0'
gem 'simple_form', '~> 3.0.2'
gem 'spring',        group: :development
gem 'rails_12factor'
gem "dotenv-rails", ">= 2.0.0"
gem "pg", "~> 0.18"
gem "unicorn"

group :development do
  gem "capistrano-bundler", :require => false
  gem "capistrano-rails", :require => false
  gem "capistrano", "~> 3.4.0", :require => false
  gem "capistrano-mb", :require => false
end
```

**Capfile**

```
require "capistrano/setup"
require "capistrano/deploy"

require "capistrano/bundler"
require "capistrano/rails"
require "capistrano/mb"
require "capistrano/rails/migrations"

Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }
```

**deploy.rb**

```
set :application, "raddit"
set :repo_url, "https://zulhfreelancer@bitbucket.org/zulhfreelancer/raddit.git"
```

**production.rb**

```
server "188.165.177.32",
       :user => "root",
       :roles => %w(app web db)
```

**About my postgres user**

```
root@vps:~# sudo -i -u postgres
postgres@vps:~$ psql
postgres=# \conninfo
You are connected to database "postgres" as user "postgres" via socket in "/var/run/postgresql" at port "5432".
```

**database.yml**

```
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rd_development

test:
  <<: *default
  database: rd_test

production:
  <<: *default
  host: localhost
  username: postgres
  password: abcd1234
  database: postgres
```

**Note**: I entered `abcd1234` as my pg password during `bundle exec cap production provision:14_04` step.

I believe I get this error because of pending migration. Running `cap production deploy:migrate` showing no error.

What am I missing here?

Please help. This is my first time deploying Rails app to VPS using capistrano and capistrano-mb.
